### PR TITLE
added CRUD to server.js

### PR DESCRIPTION
**Pull request by Malyarc**

### CODE REVIEW

**Review by Joseph765 — APPROVED** [review]
LGTM!

**Review by Joseph765 — APPROVED** [review]
Looks great!

**Review by Joseph765 — COMMENTED** [review]
Wow! Just incredible I don't even know what to say...

**Review by ikheraj17 — APPROVED** [review]
Amazing, you are a total genius

**Review by Eli-Caraballo — COMMENTED** [review]
Get out of our repo or I'll find you...

**Pull request closed without merging**
